name: Android CI

on:
  push:
    branches: [ "5.7.9" ]
  workflow_dispatch:

jobs:
  build:
    # 🌟 绝杀：不用最新系统了！强行指定使用 2020 年的 Ubuntu 服务器环境
    # 完美契合老版本 Gradle，彻底告别所有因为 SDK 太新导致的解析崩溃！
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    # 没有任何花里胡哨的删除、断网操作，直接老机器跑老代码！
    - name: Build with Gradle
      run: ./gradlew :app:assembleRelease --no-daemon

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: AutoX-v5.7.9-Release-APK
        path: app/build/outputs/apk/release/*.apk
