name: Android CI

on:
  push:
    branches: [ "5.7.9" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    # 不再使用有缓存的 Java 环境，彻底清空之前的 404 失败记录！
    - name: set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Pre-install Exact SDKs
      run: |
        yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platforms;android-29" "build-tools;29.0.2" "build-tools;29.0.3" "platforms;android-30" "build-tools;30.0.3"

    - name: Nuke Future SDKs & Disable Cloud Download
      run: |
        rm -rf $ANDROID_HOME/platforms/android-3[1-9]*
        rm -rf $ANDROID_HOME/build-tools/3[1-9]*
        rm -rf $ANDROID_HOME/system-images/*
        echo "" >> gradle.properties
        echo "android.builder.sdkDownload=false" >> gradle.properties

    # 👑 偷梁换柱大法：拦截 Gradle，将绝版的 1.6 强行替换为开源社区验证过绝对可用的哈希版本！
    - name: Inject God Mode Substitution Strategy
      run: |
        cat <<EOF > init.gradle
        allprojects {
            repositories {
                maven { url 'https://maven.aliyun.com/repository/jcenter' }
                maven { url 'https://jitpack.io' }
                mavenCentral()
                google()
            }
            configurations.all {
                resolutionStrategy.eachDependency { DependencyResolveDetails details ->
                    if (details.requested.group == 'com.github.Stericson' && details.requested.name == 'RootShell') {
                        details.useVersion '89c3b49401'
                    }
                    // 顺手把 RootTools 也防范性替换掉，防止它俩连环报错！
                    if (details.requested.group == 'com.github.Stericson' && details.requested.name == 'RootTools') {
                        details.useVersion '10fd55fb6d'
                    }
                }
            }
        }
        EOF

    - name: Build with Gradle
      run: ./gradlew --init-script init.gradle :app:assembleRelease -x lint -x lintVitalDevRelease -x lintVitalMarketRelease -x lintVitalCommonRelease --no-daemon

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: AutoX-v5.7.9-Release-APK
        path: app/build/outputs/apk/release/*.apk
